// This component was generated by @sitecore-search/cli on Mon Aug 05 2024 08:51:27 GMT+0000 (Coordinated Universal Time)

type QueryResultsSummaryProps = {
  currentPage: number;
  itemsPerPage: number;
  totalItemsReturned: number;
  totalItems: number;
};
const QueryResultsSummary = ({
  currentPage,
  itemsPerPage,
  totalItems,
  totalItemsReturned,
}: QueryResultsSummaryProps) => {
  return (
    <div className="font-bold my-auto mx-0 dark:text-white">
      Showing {itemsPerPage * (currentPage - 1) + 1} -{" "}
      {itemsPerPage * (currentPage - 1) + totalItemsReturned} of {totalItems}{" "}
      results
    </div>
  );
};

export default QueryResultsSummary;
