// This component was generated by @sitecore-search/cli on Mon Aug 05 2024 08:51:27 GMT+0000 (Coordinated Universal Time)

import { useSearchResultsActions } from "@sitecore-search/react";
import { Select, SortSelect } from "@sitecore-search/ui";

type ResultsPerPageProps = {
  defaultItemsPerPage: number;
};

const ResultsPerPage = ({ defaultItemsPerPage }: ResultsPerPageProps) => {
  const { onResultsPerPageChange } = useSearchResultsActions();
  return (
    <div>
      <label className="pr-1 dark:text-white">Results Per Page</label>
      <Select.Root
        defaultValue={String(defaultItemsPerPage)}
        onValueChange={(v) =>
          onResultsPerPageChange({
            numItems: Number(v),
          })
        }
      >
        <Select.Trigger className="cursor-pointer inline-flex items-center bg-transparent h-10 gap-1 p-2 border-gray-600 border-2 rounded focus:outline-gray-500 dark:text-white">
          <Select.SelectValue />
          <Select.Icon />
        </Select.Trigger>
        <Select.SelectContent className="bg-gray-200 dark:bg-gray-600 rounded w-full z-[100] absolute top-12 focus-within:border-gray-600">
          <Select.Viewport className="p-1">
            <Select.SelectItem
              value="24"
              className="flex items-center leading-none cursor-pointer select-none whitespace-no-wrap h-6 px-1 hover:bg-gray-900  hover:text-white data-[state=checked]:font-bold data- focus:outline-gray-400"
            >
              <SortSelect.OptionText>24</SortSelect.OptionText>
            </Select.SelectItem>

            <Select.SelectItem
              value="48"
              className="flex items-center leading-none cursor-pointer select-none whitespace-no-wrap h-6 px-1 hover:bg-gray-900  hover:text-white data-[state=checked]:font-bold data- focus:outline-gray-400"
            >
              <SortSelect.OptionText>48</SortSelect.OptionText>
            </Select.SelectItem>

            <Select.SelectItem
              value="64"
              className="flex items-center leading-none cursor-pointer select-none whitespace-no-wrap h-6 px-1 hover:bg-gray-900  hover:text-white data-[state=checked]:font-bold data- focus:outline-gray-400"
            >
              <SortSelect.OptionText>64</SortSelect.OptionText>
            </Select.SelectItem>
          </Select.Viewport>
        </Select.SelectContent>
      </Select.Root>
    </div>
  );
};

export default ResultsPerPage;
