// This component was generated by @sitecore-search/cli on Mon Aug 05 2024 08:51:27 GMT+0000 (Coordinated Universal Time)

import { CheckIcon } from "@radix-ui/react-icons";
import type { SearchResponseFacet } from "@sitecore-search/react";
import { useSearchResultsActions } from "@sitecore-search/react";
import {
  AccordionFacets,
  FacetItem,
  SearchResultsAccordionFacets,
} from "@sitecore-search/ui";

type SearchFacetsProps = {
  facets: SearchResponseFacet[];
};

const SearchFacets = ({ facets }: SearchFacetsProps) => {
  const { onFacetClick } = useSearchResultsActions();
  return (
    <SearchResultsAccordionFacets
      defaultFacetTypesExpandedList={[]}
      onFacetTypesExpandedListChange={() => {}}
      onFacetValueClick={onFacetClick}
      className="w-full"
    >
      {facets.map((f) => (
        <AccordionFacets.Facet
          facetId={f.name}
          key={f.name}
          className="block border-b mb-4 pb-4 border-gray-200"
        >
          <AccordionFacets.Header className="flex">
            <AccordionFacets.Trigger className="text-sm md:text-base font-semibold focus:outline-gray-500">
              {f.label}
            </AccordionFacets.Trigger>
          </AccordionFacets.Header>
          <AccordionFacets.Content className="mt-8">
            <AccordionFacets.ValueList className="list-none mt-2 flex flex-col space-y-2">
              {f.value.map((v, index: number) => (
                <FacetItem
                  {...{
                    index,
                    facetValueId: v.id,
                  }}
                  key={v.id}
                  className="group flex items-center text-sm cursor-pointer"
                >
                  <AccordionFacets.ItemCheckbox className="form-checkbox flex-none w-5 h-5 border border-gray-300 rounded cursor-pointer transition duration-500 ease-in-out hover:border-heading focus:outline-gray-500 aria-checked:bg-black aria-checked:dark:bg-white aria-checked:hover:bg-heading aria-checked:focus:bg-heading">
                    <AccordionFacets.ItemCheckboxIndicator className="text-white dark:text-black w-5 h-5 ">
                      <CheckIcon />
                    </AccordionFacets.ItemCheckboxIndicator>
                  </AccordionFacets.ItemCheckbox>
                  <AccordionFacets.ItemLabel className="text-sm ms-4 -mt-0.5">
                    {v.text} {v.count && `(${v.count})`}
                  </AccordionFacets.ItemLabel>
                </FacetItem>
              ))}
            </AccordionFacets.ValueList>
          </AccordionFacets.Content>
        </AccordionFacets.Facet>
      ))}
    </SearchResultsAccordionFacets>
  );
};

export default SearchFacets;
